### PR TITLE
Adding validation for paths starting with "/". Fixes issue #77.

### PR DESCRIPTION
**Pull request by MarkHerhold**
Adding a validation check for paths starting with "/". Note that this PR maintains the replace-all behavior when path is emptystring.

Fixes issue #77

### CODE REVIEW

**Comment by MarkHerhold** [comment]
Ping @tomalec or @joozek78  please review when you get a chance. Thanks!

**Comment by joozek78** [comment]
Please add your change to duplex spec. You can see the test failing in `test/SpecRunnerDuplex.html`

**Comment by tomalec** [comment]
Thanks!

> Please include your change in duplex spec too

Other than that, LGTM :)

**Comment by MarkHerhold** [comment]
Updated. I admit I'm not sure why these files don't share common code.

**Comment by tomalec** [comment]
Thanks @MarkHerhold ! :)

**Pull request merged**
