### PR TITLE
generate respects toJSON

### PR DESCRIPTION
**Pull request by EricBourland**
fix for issue #144

### CODE REVIEW

**Comment by tomalec** [comment]
@warpech WDYT? There is no significant difference according to Travis and it affects only `-duplex`.
`toJSON` could cover more JS objects in more standardized way.

I'd take it.

@EricBourland Could you change indentations to match the rest of the file.

**Comment by alshakero** [comment]
@tomalec I guess a problem would arise if there happened to be a deep object that has `toJSON` method in it. It won't fail but won't be used, right?

**Comment by tomalec** [comment]
ah! you're right, we need it inside `_generate`

**Comment by EricBourland** [comment]
okay, fixed spacing and moved it into _generate plus another test for a nested object

**Comment by warpech** [comment]
I think that this is a fair point to respect `toJSON()`, I agree with the PR.

**Comment by warpech** [comment]
@alshakero can you pls review the current code? Are there any side effects that can hurt us with Starcounter?

**Comment by alshakero** [comment]
Starcounter Helloworld works perfectly.
All 72 PuppetJs specs passed.

**Comment by warpech** [comment]
Will we be able to support this in ES6 Proxy version?

**Comment by alshakero** [comment]
I thought about it and I think it's irrelevant there. There is no cloning, we only watch for changes. But will think more about it. Please keep this open.

**Comment by alshakero** [comment]
Sorry I mean keep #144 open.

**Comment by alshakero** [comment]
Could we merge this so I fix conflicts with my PR?

**Comment by tomalec** [comment]
Merged and released as [1.1.5](https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/1.1.5)

**Pull request merged**
