### PR TITLE
Fix for issue #83

### LINKED ISSUE #83: compare function does not distinguish between 0 and empty string
When executing the following code, I would expect a difference, but compare actually returns an empty array:

``` javascript
var diff = jsonpatch.compare({value: 0}, {value: ""});
```

### PR DESCRIPTION
**Pull request by mweathers**
Fixes #83.

### CODE REVIEW

**Comment by MarkHerhold** [comment]
@mweathers Wow 😱 

Nice catch and fix.

**Comment by arosequist** [comment]
We're using this library pretty heavily, and issues #83 and #123 are causing us some production problems. What's the process for getting this PR and #127 merged and a new release published?

**Comment by tomalec** [comment]
Thanks @mweathers for a fix :) 
It's released as [1.1.2](https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/1.1.2)

**Comment by tomalec** [comment]
@arosequist Unfortunately, the process is still very manual and requires one of quite few people in our team to review it, test it, run benchmarks and merged it ;)

I would try to get the permisions to move the repo to the separate organization ([PuppetJs](https://github.com/PuppetJs/PuppetJs/)) and setup Travis CI, as mentioned at https://github.com/Starcounter-Jack/JSON-Patch/issues/108

**Pull request merged**
