### PR TITLE
Proxies, Benchmarks, ES6 modules

### PR DESCRIPTION
**Pull request by alshakero**
Changes: 

1. Added json-observe module, with its tests `npm run test-proxy` and benchmarks `npm run bench-proxy`. And it's ~220% faster than the old version, at least on my machine 🎉😁. Tests and benchmarks work on browser and CLI, you can see them you live here [here](https://alshakero.github.io/JSON-Patch/test/SpecRunnerProxy.html).

2. Fixed ES6 import. For all the three modules `json-patch`, `json-patch-duplex` and `json-observer`.
For now it's:

|               | ES6                                       | CJS                                       |
|---------------|-------------------------------------------|-------------------------------------------|
| json-patch    | import jsonpatch from './json-patch'      | var jsonpatch = require('./json-patch')     |
| json-patch-duplex    | import jsonpatch from './json-patch-duplex'      | var jsonpatch = require('./json-patch-duplex')     |
| json-observer | import JsonObserver from './json-observe' | var JsonObserver = require('./json-observer'); |

_As you can see, this doesn't break the current usage._

3. As a by-product, #129 is fixed too.

4. For proxies, #125 is fixed now, I also implemented  a test unit for it. 

5. Regarding #111, I honestly couldn't see the point. AMD isn't mainstream for Node and it depends on a [package that isn't popular at all](https://github.com/jrburke/amdefine), and isn't maintained frequently, the last commit was two months ago, and it's the best one because it is officially listed on the [RequireJS documentation](http://requirejs.org/docs/node.html). I might be wrong and it's purposeful, it takes 5 mins to implement (in `tsconfig` changing `"module": "commonjs"` to `"amd"` will do all the work, yet I don't see the point. If you know the point please advise. 

4. Last and actually least, invested 5 mins to enhance the Jasmine UI a bit, I couldn't live with it. Now we have this: 
image

What's next? Updating readme.md. It's ready BTW, but needs proof-reading and didn't want to make the PR even longer.

### CODE REVIEW

**Comment by alshakero** [comment]
@tomalec done 💃

**Comment by MarkHerhold** [comment]
I hope that we have no plans to add the entire underscore library as a dependency.

**Comment by alshakero** [comment]
I dropped this PR. @tomalec didn't like the commit messages and how big it is. And I guess he is right.

As for _underscore_, it's a **dev**Dependency, and it's used in the tests that I didn't implement. I merely added it to stop the error.

**Comment by warpech** [comment]
Hopefully all problems solved in this PR will be presented again, as separate PRs?

**Comment by alshakero** [comment]
Yes, everything will be in place step by step. I guess it's a good idea to pay some extra effort get along with your conventions for the first couple days. All the code I've written is preserved.

**Pull request closed without merging**
