### PR TITLE
Adding triple equals check to avoid worst case

### PR DESCRIPTION
**Pull request by KamranAsif**
Currently we walk through the entire subtree of the object. This change allows us to exit early if we see two objects with the same reference at a higher level. 

I wasn't able to get the tests to work locally

### CODE REVIEW

**Comment by tomalec** [comment]
Thanks for feedback, but I'm not quite sure I get your case. Could you add a test for that?

> I wasn't able to get the tests to work locally

At which step it fails? https://github.com/Starcounter-Jack/JSON-Patch/blob/master/CONTRIBUTING.md#testing

**Comment by KamranAsif** [comment]
All tests are failing both in node and in browser, with this error:

```
OPERATION_PATH_UNRESOLVABLE: Cannot perform the operation at a path that does not exist  OPERATION_PATH_UNRESOLVABLE: Cannot perform the operation at a path that does not exist
      at JsonPatchError.Error (native)
      at new JsonPatchError (JSON-Patch/src/json-patch-duplex.js:493:32)
      at Object.validator (JSON-Patch/src/json-patch-duplex.js:560:27)
      at Object.apply (JSON-Patch/src/json-patch-duplex.js:433:34)
      at Object.validate (JSON-Patch/src/json-patch-duplex.js:587:23)
      at Object.<anonymous> (JSON-Patch/test/spec/validateSpec.js:273:31)
      at attemptSync (JSON-Patch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1950:24)
      at QueueRunner.run (JSON-Patch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1938:9)
      at QueueRunner.execute (JSON-Patch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1923:10)
      at Spec.queueRunnerFactory (JSON-Patch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:714:35)
```

I'm not sure how to add a test for this change, since its a performance improvement instead of a normal bug fix. For example:
```
var largeObj = {....}
compare(largeObj, largeObj); //should be O(1) instead of O(n)
```

**Comment by tomalec** [comment]
> I'm not sure how to add a test for this change, since its a performance improvement instead of a normal bug fix. For example:
> ```js
> var largeObj = {....}
> compare(largeObj, largeObj); //should be O(1) instead of O(n)
> ```

Thanks, that makes a perfect sense. However we could add another benchmark for it

---

> All tests are failing both in node and in browser, with this error:

That's wierd, I have just cloned a fresh repo,and everything works fine.
```sh
git clone https://github.com/Starcounter-Jack/JSON-Patch.git
cd JSON-Patch
npm install
npm test
npm run bench-duplex
```

Could you provide a full log?
In the meantime I'd try to write a new bench

**Comment by tomalec** [comment]
I have added such case https://github.com/Starcounter-Jack/JSON-Patch/pull/153/commits/3a020d01e70029d2eec35d4181b9d5d357963e6c Please tell me, is that what you were talking about?

Anyways the difference is huge! So, we will definitely take this. But I'd like to check that there is nothing more to add.

**Comment by KamranAsif** [comment]
@tomalec Looks like the tests are working. Must have been something about my fork. 

The benchmarks look good. Might be worth adding a test for large arrays as well?

**Comment by KamranAsif** [comment]
Would it be worth moving the check to the top of _generate, so we can capture the case of 
```
var largeIntArray = [....]
compare(largeIntArray, largeIntArray); //This will still run in O(n) time
```

**Comment by tomalec** [comment]
> Would it be worth moving the check to the top of _generate

Would you mind doing that?

**Comment by tomalec** [comment]
> Out of curiosity, do you have some before & after numbers?

Here you have numbers before https://travis-ci.org/Starcounter-Jack/JSON-Patch#L637

You can check numbers after by merging with master :)

**Comment by tomalec** [comment]
@KamranAsif please let me know once you are finished with changes, so I'll merge this.

**Comment by alshakero** [comment]
Moving to top made it 123% faster! (37402/30403 op/sec) 🎉

**Comment by KamranAsif** [comment]
Done :)

**Comment by tomalec** [comment]
But in total this change for object deep for 11 nodes gave us, waaay much better result
37 402 : 60 083 511 
Thanks a lot @KamranAsif

**Comment by tomalec** [comment]
Released as [1.1.7](https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/1.1.7)

**Pull request merged**
