### PR TITLE
fix issues #76 by using deep clone

### PR DESCRIPTION
**Pull request by baranga**
fixes issue #76 by using deep clone

### CODE REVIEW

**Comment by tomalec** [comment]
Thanks for the PR and sorry for the late response.

I'm afraid deepCloning everywhere could affect performance.

If it's only the case of `validate` maybe we could user cloning `ops` only there?

**Comment by baranga** [comment]
@tomalec the issue not only occurs in `validate` but also in `apply` (which gets called internally). So yes, its bad for performance, but modifying the patch set in sake of speed is no option. I would be happy for any alternative, but as long as the implementation needs to modify the applied patch set it should be cloned completely.

I can provide a updated PR based on the actual release with a solution using deep clone. If you can provide a change of the implementation I would like to see it. I'm not deep enough into it to solve this.

**Comment by baranga** [comment]
I close this in favor over the new PR #134.

**Comment by tomalec** [comment]
> but modifying the patch set in sake of speed is no option

I totally agree.

But, such number of deepclones looks scary to me. 

(let's continue in #134)

**Pull request closed without merging**
