### PR TITLE
Add change observer

### PR DESCRIPTION
**Pull request by warpech**
As discussed in https://github.com/PuppetJs/PuppetJs/issues/106

Observe one additional DOM event: `change`.

### CODE REVIEW

**Comment by warpech** [comment]
@tomalec ping

**Comment by tomalec** [comment]
LGTM, merged

**Comment by warpech** [comment]
Thanks! Could you please release a version?

**Comment by tomalec** [comment]
Done [1.1.3](https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/1.1.3)

**Pull request merged**
