### PR TITLE
Ignore tsconfig.json when publishing to npm

### PR DESCRIPTION
**Pull request by LinusU**
This file is making my VisualStudio Code complain that there is no source files matching the pattern in this config file (which there isn't since they are already ignored).

> file: 'file:///my-app-dir/node_modules/fast-json-patch/tsconfig.json'
severity: 'Error'
message: 'No inputs were found in config file '/my-app-dir/node_modules/fast-json-patch/tsconfig.json'. Specified 'include' paths were '["src/**/*.ts"]' and 'exclude' paths were '["lib/"]'.'
at: '1,1'
source: 'ts'

### CODE REVIEW

**Comment by alshakero** [comment]
It's so nice of you that this is a PR, not an issue. Thanks a million.

**Comment by LinusU** [comment]
Friendly bump 😄

**Comment by LinusU** [comment]
Thanks 🍻

**Comment by alshakero** [comment]
Released 2.0.6 https://github.com/Starcounter-Jack/JSON-Patch/releases/tag/v2.0.6

**Comment by LinusU** [comment]
@alshakero seems like you missed publishing to npm, would you mind? 😄

**Comment by alshakero** [comment]
Oh damn, done https://www.npmjs.com/package/fast-json-patch

**Comment by LinusU** [comment]
Thanks!

**Pull request merged**
