### PR TITLE
add param mutateDocument in function applyPatch

### PR DESCRIPTION
**Pull request by chochihim**
I don't like `applyPatch` mutate my data so I add param `mutateDocument` like `applyOperation`. In my opinion, it is better to not mutate original data by default. However, I set the default value as `true` for the sake of consistency.

### CODE REVIEW

**Comment by chochihim** [comment]
@alshakero Which spec file should I put the test in?

**Comment by alshakero** [comment]
You can add them in this file under this describe (https://github.com/Starcounter-Jack/JSON-Patch/blob/master/test/spec/coreSpec.js#L963).

And it's super easy, you can almost copy and paste these lines, execpt you have to use `applyPatch` and a patch, not an operation: https://github.com/Starcounter-Jack/JSON-Patch/blob/f7e15daf3d6a8d1d3750b814413372a7ccf39ce9/test/spec/coreSpec.js#L487-L505

**Comment by chochihim** [comment]
Thanks for guiding me! I have added the test. Please let me know if you find any problem.

**Comment by alshakero** [comment]
Thank you so much!

**Pull request merged**
