### PR TITLE
Follow TS best practices

### LINKED ISSUE #146: Remove TS code and add Typings
After our discussion regarding PuppetJS, it makes sense to apply the same arguments and remove TS code and keep a maintained `typings` file for TS users.

@warpech WDYT?

P.S: I consulted @tomalec already.

### PR DESCRIPTION
**Pull request by felixfbecker**
This changes the npmignore, gitignore, tsconfig an package.json to follow TypeScript best practices:

- Only publish .js and .d.ts on NPM, not .ts
- Don't commit compiled .js and .d.ts to git

Commit https://github.com/Starcounter-Jack/JSON-Patch/commit/ee3340ea135a0e3b9f5ad0a83f40b400fa4db091 added a `typings` field that points to the TS source file, which made our build break in a non-major version. This fixes it by distributing a proper .d.ts file.

Closes #146

### CODE REVIEW

**Comment by alshakero** [comment]
Thank you for the PR. But we need `dist` folder in the repo, you might ignore it in `npmignore` but please don't in `gitignore`. We sometimes use rawgit CDN and would like to have the minified/bundled files in there. 

And your commit seems to remove JS files?

**Comment by felixfbecker** [comment]
Done.

**Comment by alshakero** [comment]
@felixfbecker Travis won't pass unless there are JS files in `src` folder. It's not your fault anymore. Removing JS files from `src` will break a lot of apps.

Thank you so much and please give us sometime to discuss it.

@tomalec should I modify the tests to point to `dist` folder, which I believe is a better practice, or should we add JS files in `src` again? I know you reference this file a lot. Please advise.

**Comment by felixfbecker** [comment]
I can modify the config to emit .d.ts and .js in src and still npmignore .js, if that would result in this being merged & released asap. I just found it a bit weird you would have the minified JS in dist and the compiled JS in src.

**Comment by felixfbecker** [comment]
Done

**Comment by felixfbecker** [comment]
Test failures seem unrelated? I didn't change the source at all

**Comment by alshakero** [comment]
Could you tell me your TS version. This bit me once, it's a TS bug regarding `this`. Try to compile with TSC 2.0 and run tests locally if you want to save some time.

**Comment by alshakero** [comment]
@felixfbecker I appreciate your speed man! A legend indeed.

@tomalec looks perfect to me, could you please release if you agree?

**Pull request merged**
