### PR TITLE
Update to add old_value in the output

### PR DESCRIPTION
**Pull request by JnBrewsterGT**
I would really like to have the output not only have the value changed / added but also the old value.

### CODE REVIEW

**Comment by JnBrewsterGT** [comment]
Makes sense these tests would fail.

**Comment by alshakero** [comment]
Hey! I was just responding to your email!

Thanks for your interest. First, I'm sorry but we can't do exactly that because those operations follow an RFC standard and they can't have `oldValue`. You can see [here ](http://tools.ietf.org/html/rfc6902). An operation can only have `op`, `path` and `value`. `move` and `copy` operations can have `from`. `oldValue` doesn't fit.

**However**

We have the same situation you're facing, and that's why we return `results` array! `applyPatch` function returns an array of all the old values that have been removed or replaced. You could use that instead.

Every operation returns an OperationResult object that has `removed` property set with the old value. You can find all the information [here ](https://github.com/Starcounter-Jack/JSON-Patch#operationresult-type).

**Comment by JnBrewsterGT** [comment]
OK, makes sense. You can remove/close/reject this pr.  Thanks.

**Comment by JnBrewsterGT** [comment]
Ok, thank you, I closed/denied the pr.


I appreciate you getting back to me so quickly.


John


__________________

John R. Brewster
Research Scientist

Information and Communications Laboratory (ICL)
Trusted Interoperable Systems & Architecture Division (TISAD)
Systems Architecture & Development Operations Branch (SADO)

Georgia Tech Research Institute
John.Brewster@GTRI.gatech.edu
Office: 404.407.8452

________________________________

**Pull request closed without merging**
